
# Auto-generated by Interface Designer
#
# WARNING: Any manual changes made to this file will be lost when generating constraints.

# Efinity Interface Designer SDC
# Version: 2024.1.163
# Date: 2024-10-13 20:24

# Copyright (C) 2013 - 2024 Efinix Inc. All rights reserved.

# Device: T120F324
# Project: test_project
# Timing Model: C4 (final)
